import type { Book } from "@/types";
const endpoint = "https://openlibrary.org";
const categoryQueries: Record<string, string> = { "Fantastik":"fantasy", "Bilim Kurgu":"science fiction", "Romantik":"romance", "Macera":"adventure", "Polisiye":"mystery", "Gerilim":"thriller", "Korku":"horror", "Tarihi":"historical fiction", "Dram":"drama", "Komedi":"humor", "Klasikler":"classic literature" };
type Doc={key:string;title:string;author_name?:string[];subject?:string[];cover_i?:number;first_publish_year?:number;edition_count?:number;isbn?:string[]};
const toBook=(d:Doc):Book=>({id:d.key,slug:d.key.replace('/works/',''),title:d.title,author:d.author_name?.[0]??'Bilinmeyen yazar',category:d.subject?.[0]??'Genel',cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:null,publishedYear:d.first_publish_year,editionCount:d.edition_count,isbn:d.isbn?.[0]});
export const categories=Object.keys(categoryQueries);
export function categoryQuery(category?:string){return categoryQueries[category??'']??'fiction';}
export async function searchBooks(query:string,limit=24):Promise<Book[]>{const r=await fetch(`${endpoint}/search.json?q=${encodeURIComponent(query)}&limit=${limit}&fields=key,title,author_name,subject,cover_i,first_publish_year,edition_count,isbn`,{next:{revalidate:3600}});if(!r.ok) throw new Error('Katalog kaynağına erişilemedi.');const data=await r.json() as {docs:Doc[]};return data.docs.map(toBook)}
export async function getBook(slug:string):Promise<Book|null>{const r=await fetch(`${endpoint}/works/${encodeURIComponent(slug)}.json`,{next:{revalidate:86400}});if(!r.ok)return null;const d=await r.json() as {key:string;title:string;description?:string|{value:string};subjects?:string[];covers?:number[];first_publish_date?:string};return {id:d.key,slug,title:d.title,author:'Open Library katalog kaydı',category:d.subjects?.[0]??'Genel',cover:d.covers?.[0]?`https://covers.openlibrary.org/b/id/${d.covers[0]}-L.jpg`:null,description:typeof d.description==='string'?d.description:d.description?.value,publishedYear:d.first_publish_date?Number(d.first_publish_date.slice(0,4)):undefined}}
