import type { Book } from "@/types";
const endpoint = "https://openlibrary.org";
type OpenLibraryDoc = { key: string; title: string; author_name?: string[]; subject?: string[]; cover_i?: number; first_publish_year?: number; edition_count?: number; isbn?: string[] };
const mapBook = (book: OpenLibraryDoc): Book => ({ id: book.key, slug: book.key.replace("/works/", ""), title: book.title, author: book.author_name?.[0] ?? "Bilinmeyen yazar", category: book.subject?.[0] ?? "Genel", cover: book.cover_i ? `https://covers.openlibrary.org/b/id/${book.cover_i}-L.jpg` : null, publishedYear: book.first_publish_year, editionCount: book.edition_count, isbn: book.isbn?.[0] });
export async function searchBooks(query: string, limit = 24) { const response = await fetch(`${endpoint}/search.json?q=${encodeURIComponent(query)}&limit=${limit}&fields=key,title,author_name,subject,cover_i,first_publish_year,edition_count,isbn`, { next: { revalidate: 3600 } }); if (!response.ok) return googleSearch(query, limit); const data = await response.json() as { docs: OpenLibraryDoc[] }; return data.docs.map(mapBook); }
type GoogleItem = { id:string; volumeInfo:{title:string; authors?:string[]; categories?:string[]; imageLinks?:{thumbnail?:string}; publishedDate?:string; industryIdentifiers?:{identifier:string}[]} };
async function googleSearch(query:string, limit:number):Promise<Book[]> { const response=await fetch(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(query)}&maxResults=${Math.min(limit,40)}&projection=lite`,{next:{revalidate:3600}}); if(!response.ok) return []; const data=await response.json() as {items?:GoogleItem[]}; return (data.items??[]).map(item=>({id:`google:${item.id}`,slug:`google-${item.id}`,title:item.volumeInfo.title,author:item.volumeInfo.authors?.[0]??"Bilinmeyen yazar",category:item.volumeInfo.categories?.[0]??"Genel",cover:item.volumeInfo.imageLinks?.thumbnail?.replace("http://","https://")??null,publishedYear:item.volumeInfo.publishedDate?Number(item.volumeInfo.publishedDate.slice(0,4)):undefined,isbn:item.volumeInfo.industryIdentifiers?.[0]?.identifier})); }
export async function popularBooks() { const books=await searchBooks("subject:fiction", 12); return books.length?books:googleSearch("subject:fiction",12); }
export async function getBook(slug: string): Promise<Book | null> { const response = await fetch(`${endpoint}/works/${encodeURIComponent(slug)}.json`, { next: { revalidate: 86400 } }); if (!response.ok) return null; const data = await response.json() as { key:string; title:string; description?: string | { value: string }; subjects?: string[]; covers?: number[]; first_publish_date?: string }; return { id:data.key, slug, title:data.title, author:"Open Library katalog kaydı", category:data.subjects?.[0] ?? "Genel", cover:data.covers?.[0] ? `https://covers.openlibrary.org/b/id/${data.covers[0]}-L.jpg` : null, description:typeof data.description === "string" ? data.description : data.description?.value, publishedYear:data.first_publish_date ? Number(data.first_publish_date.slice(0,4)) : undefined } satisfies Book; }
export const categories = ["Fantastik","Bilim Kurgu","Romantik","Macera","Polisiye","Gerilim","Korku","Tarihi","Dram","Komedi","Klasikler","Çocuk Edebiyatı"];
